compatibility_date = "2022-02-21"
name = "graphql-yoga"
account_id = "f9d6328dc3115e621758a741dda3d5c4"
workers_dev = true
main = "src/index.ts"
compatibility_flags = ["streams_enable_constructors"]

[dev]
ip = "0.0.0.0"
port = 3077
local_protocol = "http"

kv_namespaces = [
  { binding = "KVDATA", preview_id = "43d5f62ebc9f4e9cafa30671613cbfa0", id = "43d5f62ebc9f4e9cafa30671613cbfa0" }
]